apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  mysql-root-password: StrongRootPass123!
  mysql-database:      wordpress
  mysql-user:          wp_user
  mysql-password:      StrongUserPass456!                     